FROM nvidia/cuda:11.8.0-base-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    dos2unix \
    libglib2.0-0 \
    libgl1-mesa-glx \
    libxext6 \
    libxrender1 \
    libsm6 \
    libfontconfig1 \
    libxkbcommon-x11-0 \
    libx11-xcb1 && \
    rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir numpy'<2.0'
RUN pip install --no-cache-dir torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118

RUN pip install --no-cache-dir \
    onnx \
    opencv-python==4.5.5.64 \
    pandas \
    tqdm \
    easydict \
    cython \
    PyYAML \
    pycocotools \
    jpeg4py \
    tb-nightly \
    thop \
    colorama \
    lmdb \
    scipy \
    visdom \
    pyarrow \
    tensorboardX \
    setuptools==59.5.0 \
    wandb \
    timm \
    tikzplotlib

WORKDIR /workspace


